# Use official Eclipse Temurin JDK 24 base image 
FROM eclipse-temurin:21-jdk

# Set working directory
WORKDIR /app

# Copy the compiled Spring Boot jar
COPY target/payment.jar app.jar

# App listens on port 8080
EXPOSE 8080

# Set Timezone to Asia/Kolkata
ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Run the Spring Boot jar
ENTRYPOINT ["java", "-jar", "app.jar"]
